spring:
  datasource:
    url: jdbc:mysql://ewhabaekjoon.ctgkgsmgmdya.ap-northeast-2.rds.amazonaws.com:3306/ewhabaekjoon
    username: QLteam
    password: QLteam1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30