name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-36-252-243.ap-northeast-2.compute.amazonaws.com << 'EOF'
            sudo su -
            cd backend
            git pull
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker rmi $(docker images -q) || true
            sh gradlew build
            docker build -t backend . 
            docker run -d -p 8080:8080 backend
          EOF
