name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Rebuild
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-36-252-243.ap-northeast-2.compute.amazonaws.com << 'EOF'
            sudo su -
            cd backend
            git pull
            echo "깃 풀"
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker rmi $(docker images -q) || true
            sh gradlew build
          EOF
      - name: Depoly
        run: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-36-252-243.ap-northeast-2.compute.amazonaws.com << 'EOF'
                echo "도커 빌드"
                docker build --progress=plain -t backend . 
                echo "도커 런"
                docker run -d -p 8080:8080 backend
            EOF
